### ISSUE TITLE
Create code-of-conduct.md

### ISSUE THREAD

**Issue by KirtiPratihar** [prayas7102/NodejsSecurify#11]
@prayas7102  I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext, hacktoberfest-accepted Labels.

Thanks

**Comment by prayas7102** [comment]
> @prayas7102 I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext, hacktoberfest-accepted Labels.
> 
> Thanks

Thanks for showing interest, What all points you've planned to add in the code of conduct?

**Comment by KirtiPratihar** [comment]
@prayas7102  I would like to formally document the following points: pledge, standards, Enforcement Guidelines, consequences of Unacceptable Behavior.

**Comment by imbev** [comment]
I suggest the Ruby Code of Conduct as inspiration: https://www.ruby-lang.org/en/conduct/

**Comment by KirtiPratihar** [comment]
@prayas7102 If any further modifications are necessary, please inform. Otherwise, you can proceed to close the issue if all matters have been resolved.

Thank you.
